### ISSUE TITLE
Timeout bei Zugriff auf ffmpeg Testpfad

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.cameras#130]
Timeout wird nach ca 5-10 Sekunden angezeigt, wenn man auf Tespfad für ffmpeg klickt.
ffmpeg wurde installiert.
`sudo apt install ffmpeg -y`

![image](https://github.com/ioBroker/ioBroker.cameras/assets/84818934/4a248338-200d-49fc-9bee-ac3e0ee143e9)

![image](https://github.com/ioBroker/ioBroker.cameras/assets/84818934/66a335f0-cbdf-48f3-82dc-fa5fdca4b944)

ffmpeg ist vorhanden
```
prox@iobrokerPROD:/usr/bin$ dir ffmpeg
ffmpeg
```

**Comment by GermanBluefox** [comment]
Please enable debug log. In this log you will see which ffmpeg command will be executed, like:
`ffmpeg -y -rtsp_transport udp -i rtsp://admin:******@192.168.178.150:554/stream=1 -loglevel error -vframes 1 /opt/iobroker/ioBroker.cameras/snapshots/192_168_178_150.jpg`

When you execute this command on CLI, you should get the jpg. Only in this case adapter can get the snapshot. Elsewise your rtsp parameters are invalid

**Comment by mcuiobroker** [comment]
Debug-Log nach Klick auf Testpfad
```
cameras.0
2023-10-15 21:02:07.158	warn	TypeError: rtsp.executeFFmpeg is not a function at processMessage (/opt/iobroker/node_modules/iobroker.cameras/main.js:191:22) at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.cameras/main.js:33:34) at Adapter.emit (node:events:514:28) at Adapter.emit (node:domain:489:12) at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:5831:34) at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37) at processImmediate (node:internal/timers:476:21)

cameras.0
2023-10-15 21:02:07.093	warn	States system pmessage io.messagebox.system.adapter.cameras.0 {"command":"ffmpeg","message":{"path":"/usr/bin/ffmpeg"},"from":"system.adapter.admin.0","callback":{"message":{"path":"/usr/bin/ffmpeg"},"id":31,"ack":false,"time":1697396527092},"_id":86131552} rtsp.executeFFmpeg is not a function

cameras.0
2023-10-15 21:00:48.545	debug	Snapshot from 192.168.178.137. Done!

cameras.0
2023-10-15 21:00:46.785	debug	Executing /usr/bin/ffmpeg -y -i rtsp://admin:*****@192.168.178.137:554/live/ch0 -loglevel error -vframes 1 /opt/iobroker/node_modules/iobroker.cameras/snapshots/192_168_178_137.jpg
```
Das Bild wird gespeichert und ist auch ok.
