### ISSUE TITLE
Errors Log

### ISSUE THREAD

**Issue by marcelk1101** [ioBroker/ioBroker.cameras#77]
Hallo, 
folgende Konfiguration bei mir mit nachfolgendem Logauszug

- Raspberry Pi 4
- NPM: v8.19.3
- Node.js: v16.19.0
- Cameras Adapter: v1.0.3

Beschreibung:

- Es sind 2 RTSP-Kameras angelegt, welche über den Button "Prüfung" ein Bild liefern.
- Die Links funktionieren nicht, hier erscheint entweder: **Invalid Key** oder **connect ECONNREFUSED 127.0.0.1:8200**
- Datenpunkte werden nicht angelegt.

Ich würde mich freuen, wenn die Fehler behoben werden könnten um RTSP-Kameras einbinden zu können.

Logauszug:

`
2023-02-04 09:21:28.552 - error: cameras.0 (13949) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

2023-02-04 09:21:28.554 - error: cameras.0 (13949) unhandled promise rejection: Cannot set headers after they are sent to the client

2023-02-04 09:21:28.560 - error: cameras.0 (13949) Error: Cannot set headers after they are sent to the client
at new NodeError (node:internal/errors:387:5)
at ServerResponse.setHeader (node:_http_outgoing:644:11)
at /opt/iobroker/node_modules/iobroker.cameras/main.js:357:41

2023-02-04 09:21:28.560 - error: cameras.0 (13949) Exception-Code: ERR_HTTP_HEADERS_SENT: Cannot set headers after they are sent to the client

2023-02-04 09:21:29.787 - error: host.raspberrypi Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

2023-02-04 09:21:29.795 - error: host.raspberrypi Caught by controller[1]: Error: Cannot set headers after they are sent to the client

2023-02-04 09:21:29.796 - error: host.raspberrypi Caught by controller[1]: at new NodeError (node:internal/errors:387:5)

2023-02-04 09:21:29.796 - error: host.raspberrypi Caught by controller[1]: at ServerResponse.setHeader (node:_http_outgoing:644:11)

2023-02-04 09:21:29.796 - error: host.raspberrypi Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.cameras/main.js:357:41

2023-02-04 09:21:29.797 - error: host.raspberrypi instance system.adapter.cameras.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

2023-02-04 09:22:37.933 - error: cameras.0 (12093) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

2023-02-04 09:22:37.936 - error: cameras.0 (12093) unhandled promise rejection: Cannot set headers after they are sent to the client

2023-02-04 09:22:37.942 - error: cameras.0 (12093) Error: Cannot set headers after they are sent to the client
at new NodeError (node:internal/errors:387:5)
at ServerResponse.setHeader (node:_http_outgoing:644:11)
at /opt/iobroker/node_modules/iobroker.cameras/main.js:357:41
`

**Comment by GermanBluefox** [comment]
Hallo @marcelk1101, sorry - dieses Issue ist dreieinhalb Jahre lang unbeantwortet liegen geblieben.

Der Adapter wurde inzwischen komplett in TypeScript neu geschrieben, die `main.js:357` aus dem Stacktrace gibt es nicht mehr. Ich habe deinen Bericht trotzdem gegen den aktuellen Code durchgearbeitet - und alle drei Symptome hatten dort noch eine Entsprechung. Fünf Fehler sind jetzt in master behoben:

**1. `connect ECONNREFUSED 127.0.0.1:8200`**
Der interne Webserver wurde erst *nach* `fillFiles()` gestartet, und `fillFiles()` holt beim Start von jeder Kamera ein Bild. Bei RTSP heißt das ffmpeg starten und warten - bei zwei RTSP-Kameras also mehrere Sekunden, in denen der Port noch gar nicht lauscht und alles, was der Web-Adapter dorthin weiterreicht, mit ECONNREFUSED scheitert. Der Server startet jetzt zuerst.

**2. „Invalid Key" - gleich drei Ursachen**

Die Liste der erlaubten IPs wurde mit `/,;/` zerlegt statt mit `/[,;]/`. Das trennt nur an der wörtlichen Zeichenfolge `,;`:

```
"192.168.1.10,192.168.1.11".split(/,;/)   =>  ["192.168.1.10,192.168.1.11"]   // ein Eintrag
```

Jede Liste mit mehr als einer Adresse war damit ein einziger Müll-Eintrag, der auf nichts passte - und jeder Zugriff außer von `127.0.0.1` wurde abgewiesen. Auch `*` wirkte nicht, sobald noch etwas dahinter stand.

Dazu wurde die Loopback-Adresse gegen `"::1/128"` verglichen - CIDR-Notation, die `socket.remoteAddress` nie liefert. Kam die Verbindung über IPv6 (`::1` oder `::ffff:127.0.0.1`), galt sie als fremd.

Beides antwortete mit **„Invalid key"**, obwohl der Key völlig in Ordnung war. Das schickt die Fehlersuche genau in die falsche Richtung, und ich vermute, das ist was du gesehen hast. Die Adressprüfung antwortet jetzt mit `403 IP not allowed`. Nebenbei stand der geheime Key im Klartext im Log - auch entfernt.

**3. Der Absturz (`ERR_HTTP_HEADERS_SENT`, Code 6)**
Der `catch` um eine fehlgeschlagene Bildanfrage schrieb ungeprüft in die Antwort. War der ursprüngliche Fehler bereits ein Header-Problem, warf der `catch` erneut - und dieser zweite Wurf verließ den `async`-Handler als unhandled rejection, woraufhin der js-controller die Instanz mit Code 6 beendet hat. Genau die Sequenz aus deinem Log. Es wird jetzt auf `headersSent`/`writableEnded` geprüft.

Dass die **Datenpunkte nicht angelegt** wurden, war sehr wahrscheinlich eine Folge davon: Wenn die Instanz beim Start immer wieder abstürzt, kommt sie nicht weit genug. Das lässt sich nachträglich nicht mehr belegen.

Und weil es beim Analysieren auffiel: die Web-Extension merkte sich die Konfiguration vom Zeitpunkt ihres Starts. Ändert man den Key, lieferte sie weiter den alten - „Invalid key" bis ioBroker.web ebenfalls neu gestartet wurde. Sie liest den Key jetzt nach einem 401 selbst nach.

Alles in `8d0b6d8`. Falls du den Adapter noch einsetzt, würde mich interessieren, ob es damit läuft.
